version: 2.1

workflows:
  main:
    jobs:
      - build
      - test-on-ubuntu:
          matrix:
            parameters:
              ubuntuVersion:
                - "18.04"
                - "20.04"
                - "22.04"
  daily:
    triggers:
      - schedule:
          cron: "30 9 * * *"
          filters:
            branches:
              only: trunk
    jobs:
      - check-minecraft-version
      - test-on-ubuntu:
          matrix:
            parameters:
              ubuntuVersion:
                - "18.04"
                - "20.04"
                - "22.04"

jobs:
  build:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - run:
          name: "Add Tests Here Soon"
          command: echo "Update this job with tests in the future."
  test-on-ubuntu:
    parameters:
      ubuntuVersion:
        type: string
    docker:
      - image: cimg/base:2023.01-<< parameters.ubuntuVersion >>
    steps:
      - checkout
      - run:
          name: "Setup Ubuntu Desktop"
          command: sudo apt-get update && sudo apt-get install -y ubuntu-desktop
      - run:
          name: "Try installing Minecraft"
          command: |
            sudo ./minecraft-mgr.sh install
            which minecraft-launcher
  check-minecraft-version:
    docker:
      - image: cimg/base:2023.01
    steps:
      - checkout
      - run:
          name: "Check if there's a new Minecraft version"
          command: |
            ./update-minecraft-version.sh

            if git status | grep -q "working tree clean"; then
              echo "No changes, exiting."
              exit
            fi

            git config --global user.email "Ricardo@Feliciano.Tech"
            git config --global user.name "Ricardo N Feliciano"

            git add ./MINECRAFT_VERSION
            git commit -m "Adding new Minecraft version."
            git push
